import { useEffect, useMemo, useState } from 'react';
import { BookOpen, ChevronDown, ChevronUp, Clipboard, ClipboardPaste, FlaskConical, Languages, Menu, Search, ShieldCheck, Sparkles, X } from 'lucide-react';

const API_BASE = import.meta.env.VITE_FORENSICS_API_BASE || '';

type Manuscript={id:string;work:string;collection:string;shelfmark:string;manuscript_date:string;language:string;script:string;diacritics_status:string;witness_status:string;witness_excerpt:string;source_url:string;notes:string};
type Analysis={detected_language:string;detection_confidence:number;summary:string;findings:{text:string;language:string;confidence:number;classification:string;evidence:string;caveat:string}[];methodological_notes:string[]};
type Dossier={witness:string;normalized:string;transliteration:string;detected_script:string;detected_language:string;detection_confidence:number;word_analysis:{witness:string;normalized:string;transliteration:string;root_or_lemma:string;gloss:string;note:string}[];root_fallbacks:string[];textual_criticism:string[];comparative_cognates:{span:string;language:string;candidate:string;classification:string;evidence:string;caveat:string}[];provider_comparison:{perspective:string;conclusion:string}[];synthesis:string;limitations:string[]};
type Probe={mode:string;language:string;result:string;forced_text:string;transliteration:string;english_translation:string;arabic_literal_translation:string;back_translation:string;plausibility:string;aligned_spans:string[];warnings:string[]};

const LANGUAGES=['Persian','Classical Syriac','Nabataean Aramaic','Imperial Aramaic','Biblical Aramaic','Jewish Babylonian Aramaic','Assyrian Neo-Aramaic','Hebrew','Akkadian','Safaitic','Hismaic','Dadanitic','Ancient North Arabian','Geʿez','Greek','Latin'];
const MANUSCRIPT_FALLBACK:Manuscript[]=[
{id:'princeton-1904Yq',work:'Ṣaḥīḥ al-Bukhārī',collection:'Princeton Manuscripts of the Islamic World',shelfmark:'Garrett no. 1904Yq',manuscript_date:'1400-1420',language:'Arabic',script:'Arabic',diacritics_status:'visible in manuscript image; not yet machine-normalized',witness_status:'digitized manuscript witness',witness_excerpt:'',source_url:'https://digital-collections.princeton.edu/i/%D8%A7%D9%84%D9%86%D8%B5%D9%81-%D8%A7%D9%84%D8%A7%D9%88%D9%84-%D9%85%D9%86-%D8%B5%D8%AD%D9%8A%D8%AD-%D8%A7%D9%84%D8%A8%D8%AE%D8%A7%D8%B1%D9%8A/item/aa217489-3c80-4821-9e4d-7ebee0afb997/viewer/7',notes:'First half of Ṣaḥīḥ al-Bukhārī; digitized manuscript record.'},
{id:'loc-1017-v3',work:'Ṣaḥīḥ al-Bukhārī',collection:'Library of Congress / National Library of Bulgaria',shelfmark:'1017 copy, Volume 3',manuscript_date:'1017',language:'Arabic',script:'Arabic',diacritics_status:'to be transcribed directly from page images',witness_status:'digitized manuscript witness',witness_excerpt:'',source_url:'https://www.loc.gov/item/2021667288/',notes:'Incomplete and fragmentary manuscript; LOC describes it as the earliest Arabic manuscript in the National Library of Bulgaria.'},
{id:'princeton-694H',work:'Ishārāt Ṣaḥīḥ al-Bukhārī wa-asānīduh',collection:'Princeton Manuscripts of the Islamic World',shelfmark:'Garrett no. 694H',manuscript_date:'1700-1799',language:'Arabic',script:'Arabic',diacritics_status:'not machine-assessed; preserve page image as authority',witness_status:'digitized manuscript witness',witness_excerpt:'سمعت النبي صلى الله عليه وسلم يقول من يقل عليّ ما لم اقل فليتبوّأ مقعده من النار',source_url:'https://digital-collections.princeton.edu/i/%D8%A7%D8%B4%D8%A7%D8%B1%D8%A7%D8%AA-%D8%B5%D8%AD%D9%8A%D8%AD-%D8%A7%D9%84%D8%A8%D8%AE%D8%A7%D8%B1%D9%8A-%D9%88%D8%A7%D8%B3%D8%A7%D9%86%D9%8A%D8%AF%D9%87-%D9%84%D9%84%D8%AD%D8%A7%D9%81%D8%B8/item/321c77-d79e-4656-9b13-31904793467d/viewer/9',notes:'Princeton metadata records this as the ending; retain it as a manuscript excerpt, not silently normalized.'},
{id:'princeton-695H',work:'Risālah tashtamilu ʿalá majālis sanad al-Imām al-Bukhārī',collection:'Princeton Manuscripts of the Islamic World',shelfmark:'Garrett no. 695H',manuscript_date:'1600-1699',language:'Arabic',script:'Arabic',diacritics_status:'not machine-assessed; preserve page image as authority',witness_status:'digitized manuscript witness',witness_excerpt:'بسم الله الرحمن الرحيم الحمد لله رب العالمين مجلس يتعلق باول صحيح البخاري',source_url:'https://digital-collections.princeton.edu/i/%D8%B1%D8%B3%D8%A7%D9%84%D8%A9-%D8%AA%D8%B4%D8%AA%D9%85%D9%84-%D8%B9%D9%84%D9%89-%D9%85%D8%AC%D8%A7%D9%84%D8%B3-%D8%B3%D9%86%D8%AF/item/55ea59d1-0631-4367-a78b-8dfc4daa9363/viewer/2',notes:'Princeton metadata gives this as the incipit. It is a treatise concerning the transmission chain of Ṣaḥīḥ al-Bukhārī.'},
{id:'qdl-2583',work:'The Lesser Compilation of Hadiths of the Consecrated Messenger',collection:'Qatar Digital Library',shelfmark:'QNLHC 2583',manuscript_date:'1685',language:'Arabic',script:'Arabic Naskh',diacritics_status:'to be assessed from manuscript images',witness_status:'digitized manuscript witness',witness_excerpt:'',source_url:'https://qdl.qa/en/archive/qnlhc/2583',notes:'380-item digitized record; late 17th-century Arabic hadith compilation attributed to Jalāl al-Dīn al-Suyūṭī.'}
];

const principles=['A manuscript witness is evidence of transmission, not automatically an authorial original.','A cognate is not automatically a borrowing. Shared inheritance, contact, coincidence and orthographic similarity are tested separately.','A forced-language reading is an experiment, not proof of original composition.','The platform does not attempt to prove or disprove a religion, political position, doctrine or community tradition.'];

async function callApi(path:string,body?:unknown){
 const res=await fetch(API_BASE+path,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined});
 if(!res.ok) throw new Error(await res.text()||'Research service request failed.');
 return res.json();
}

function App(){
 const [menu,setMenu]=useState(false); const [view,setView]=useState<'home'|'lab'|'manuscripts'|'method'|'pricing'>('home');
 const [text,setText]=useState(''); const [selected,setSelected]=useState(LANGUAGES.slice(0,13)); const [analysis,setAnalysis]=useState<Analysis|null>(null); const [dossier,setDossier]=useState<Dossier|null>(null); const [probe,setProbe]=useState<Probe|null>(null);
 const [forcedLanguage,setForcedLanguage]=useState(''); const [probeMode,setProbeMode]=useState<'translate'|'evaluate'>('translate'); const [translation,setTranslation]=useState('');
 const [manuscripts,setManuscripts]=useState<Manuscript[]>([]); const [loading,setLoading]=useState(''); const [error,setError]=useState(''); const [showLang,setShowLang]=useState(true);
 const selectedLabels=useMemo(()=>selected,[selected]);
 const go=(v:typeof view)=>{setView(v);setMenu(false);window.scrollTo({top:0,behavior:'smooth'})};
 const paste=async()=>{try{setText(await navigator.clipboard.readText());setError('')}catch{setError('Clipboard access was unavailable. Paste directly into the witness field.')}};
 const copy=async(value:string)=>{try{await navigator.clipboard.writeText(value)}catch{}};
 const analyze=async()=>{if(!text.trim())return setError('Paste the original Hadith text first.');if(selected.length<2)return setError('Select at least two comparison languages.');setLoading('analysis');setError('');setAnalysis(null);try{const r=await callApi('/api/analyze',{text:text.trim(),languages:selectedLabels});setAnalysis(r.analysis)}catch(e){setError(e instanceof Error?e.message:'Analysis failed.')}finally{setLoading('')}};
 const runDossier=async()=>{if(!text.trim())return setError('Paste the original Hadith text first.');if(selected.length<2)return setError('Select at least two comparison languages.');setLoading('dossier');setError('');setDossier(null);try{const r=await callApi('/api/forensic-dossier',{text:text.trim(),languages:selectedLabels});setDossier(r.dossier)}catch(e){setError(e instanceof Error?e.message:'Dossier failed.')}finally{setLoading('')}};
 const runProbe=async()=>{if(!text.trim())return setError('Paste the original Hadith text first.');if(!forcedLanguage)return setError('Choose one target language.');if(probeMode==='evaluate'&&!translation.trim())return setError('Provide the translation to evaluate.');setLoading('probe');setError('');setProbe(null);try{const r=await callApi('/api/forced-language',{text:text.trim(),language:forcedLanguage,mode:probeMode,translation});setProbe(r.result)}catch(e){setError(e instanceof Error?e.message:'Probe failed.')}finally{setLoading('')}};
 const loadManuscripts=async()=>{setLoading('manuscripts');setError('');setManuscripts(MANUSCRIPT_FALLBACK);try{const r=await callApi('/api/manuscripts');if(Array.isArray(r.manuscripts)&&r.manuscripts.length)setManuscripts(r.manuscripts)}catch(e){console.warn('Manuscript API unavailable; using verified local catalogue.',e)}finally{setLoading('')}};
 useEffect(()=>{if(view==='manuscripts'&&!manuscripts.length)loadManuscripts()},[view]);

 return <div className="min-h-screen">
 <header className="sticky top-0 z-30 border-b border-white/10 bg-[#07101d]/95 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 lg:px-8">
 <button onClick={()=>go('home')} className="flex items-center gap-3 text-left"><span className="grid h-10 w-10 place-items-center rounded-xl border border-[#c9a96b]/40 bg-[#c9a96b]/10 text-[#d8bd82]"><FlaskConical size={20}/></span><span><b className="block tracking-tight">HADITH TRUTHFULLY</b><small className="text-slate-500">Textual & linguistic research</small></span></button>
 <nav className="hidden items-center gap-7 text-sm text-slate-300 lg:flex"><button onClick={()=>go('lab')}>Research Lab</button><button onClick={()=>go('method')}>Methodology</button><button onClick={()=>go('manuscripts')}>Manuscripts</button><button onClick={()=>go('pricing')}>Pricing</button></nav>
 <div className="flex items-center gap-3"><button className="lg:hidden" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button><button onClick={()=>go('lab')} className="hidden rounded-lg bg-[#c9a96b] px-4 py-2 text-sm font-bold text-[#07101d] lg:block">Open Research Lab</button></div></div>
 {menu&&<nav className="border-t border-white/10 px-5 py-4 lg:hidden"><div className="flex flex-col gap-4 text-slate-300"><button className="text-left" onClick={()=>go('lab')}>Research Lab</button><button className="text-left" onClick={()=>go('method')}>Methodology</button><button className="text-left" onClick={()=>go('manuscripts')}>Manuscripts</button><button className="text-left" onClick={()=>go('pricing')}>Pricing</button></div></nav>}</header>

 {view==='home'&&<main><section className="mx-auto grid max-w-7xl gap-12 px-5 pb-24 pt-20 lg:grid-cols-[1.15fr_.85fr] lg:px-8 lg:pt-28"><div><div className="mb-5 inline-flex items-center gap-2 rounded-full border border-[#c9a96b]/30 bg-[#c9a96b]/10 px-3 py-1.5 text-xs font-semibold uppercase tracking-[.18em] text-[#d8bd82]"><ShieldCheck size={14}/>Neutral research by design</div><h1 className="serif text-5xl leading-[1.02] tracking-tight text-white lg:text-7xl">Read the Text.<br/><span className="text-[#d8bd82]">Examine the Witness.</span><br/>Follow the Evidence.</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-slate-300">A manuscript-grounded research laboratory for linguistic, phonological and textual-critical analysis of Hadith traditions.</p><div className="mt-8 flex flex-wrap gap-3"><button onClick={()=>go('lab')} className="rounded-xl bg-[#c9a96b] px-5 py-3 font-bold text-[#07101d]">Start researching →</button><button onClick={()=>go('method')} className="rounded-xl border border-white/15 px-5 py-3 font-semibold text-slate-200">How it works</button></div><p className="mt-5 text-xs text-slate-500">Not a religious argument engine. Not a political tool. A textual research instrument.</p></div><div className="rounded-3xl border border-white/10 bg-white/[.035] p-6 shadow-2xl lg:p-8"><p className="text-xs uppercase tracking-[.2em] text-[#d8bd82]">Research pipeline</p><h2 className="mt-2 text-xl font-semibold">From witness to assessment</h2><div className="mt-6 space-y-3">{['Witness — preserve the supplied wording','Normalize — separate diplomatic from normalized','Phonology — test sound correspondences','Lexicon — roots, lemmas and semantic range','Compare — cognacy, borrowing and contact','Critique — transmission and scribal hazards'].map((x,i)=><div key={x} className="rounded-2xl border border-white/8 bg-black/10 p-4 text-sm text-slate-300"><b className="mr-3 text-[#d8bd82]">0{i+1}</b>{x}</div>)}</div></div></section>
 <section className="border-y border-white/10 bg-black/10"><div className="mx-auto max-w-7xl px-5 py-20 lg:px-8"><div className="grid gap-4 md:grid-cols-3"><Feature title="Comparative language" text="Test Arabic against selected Semitic and classical languages without collapsing cognacy into borrowing." icon={<Languages/>}/><Feature title="Manuscript witnesses" text="Keep witness text distinct from normalization, metadata and later analytical layers." icon={<BookOpen/>}/><Feature title="Audit-minded output" text="Record caveats, alternatives and evidence status instead of presenting speculation as fact." icon={<ShieldCheck/>}/></div></div></section></main>}

 {view==='lab'&&<ResearchLab text={text} setText={setText} selected={selected} setSelected={setSelected} showLang={showLang} setShowLang={setShowLang} loading={loading} error={error} analysis={analysis} dossier={dossier} probe={probe} forcedLanguage={forcedLanguage} setForcedLanguage={setForcedLanguage} probeMode={probeMode} setProbeMode={setProbeMode} translation={translation} setTranslation={setTranslation} analyze={analyze} runDossier={runDossier} runProbe={runProbe} paste={paste} copy={copy}/>}
 {view==='manuscripts'&&<ManuscriptPage manuscripts={manuscripts} loading={loading} error={error} onReload={loadManuscripts} onUse={t=>{setText(t);go('lab')}}/>}
 {view==='method'&&<MethodPage/>}
 {view==='pricing'&&<PricingPage/>}
 <footer className="border-t border-white/10"><div className="mx-auto flex max-w-7xl flex-col gap-3 px-5 py-8 text-sm text-slate-500 lg:flex-row lg:items-center lg:justify-between lg:px-8"><span>© Hadith Truthfully · Textual, linguistic & manuscript research</span><span>Neutral by design · Evidence-led by method</span></div></footer>
 </div>
}

function safeExternalUrl(value:string){try{const u=new URL(value);return u.protocol==='https:'?u.toString():'#'}catch{return '#'}}

function Feature({title,text,icon}:{title:string;text:string;icon:React.ReactNode}){return <div className="rounded-2xl border border-white/10 p-6"><div className="text-[#d8bd82]">{icon}</div><h3 className="mt-5 font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-400">{text}</p></div>}

function ResearchLab(p:any){return <main className="mx-auto max-w-7xl px-5 py-10 lg:px-8"><div className="mb-8"><p className="text-xs font-bold uppercase tracking-[.2em] text-[#d8bd82]">Research Lab</p><h1 className="serif mt-2 text-4xl text-white lg:text-5xl">Controlled Hadith philology.</h1><p className="mt-3 max-w-3xl text-slate-400">The supplied witness remains the primary object. Analytical transformations are displayed separately.</p></div>{p.error&&<div className="mb-5 rounded-xl border border-red-900 bg-red-950/40 p-4 text-sm text-red-300">{p.error}</div>}
 <div className="grid gap-6 xl:grid-cols-[1fr_420px]"><div className="space-y-5"><section className="rounded-2xl border border-white/10 bg-white/[.025] p-5"><div className="mb-3 flex items-center justify-between"><label className="font-semibold">Original Hadith witness</label><span className="text-xs text-slate-500">{p.text.length.toLocaleString()} characters</span></div><textarea value={p.text} onChange={(e:any)=>p.setText(e.target.value)} dir="auto" placeholder="Paste the exact Arabic witness here…" className="min-h-[300px] w-full rounded-xl border border-slate-700 bg-slate-950 p-4 font-serif text-lg leading-8 text-slate-100 outline-none focus:border-amber-400"/><div className="mt-3 flex flex-wrap gap-2"><button onClick={p.paste} className="flex items-center gap-2 rounded-lg border border-slate-700 px-3 py-2 text-xs text-slate-300"><ClipboardPaste size={15}/>Paste clipboard</button><button onClick={()=>p.copy(p.text)} className="flex items-center gap-2 rounded-lg border border-slate-700 px-3 py-2 text-xs text-slate-300"><Clipboard size={15}/>Copy witness</button><button onClick={()=>{p.setText('');}} className="rounded-lg border border-slate-700 px-3 py-2 text-xs text-slate-300">Clear</button></div><div className="mt-4 grid gap-2 sm:grid-cols-2"><button disabled={!!p.loading} onClick={p.analyze} className="rounded-xl bg-[#c9a96b] px-4 py-3 font-bold text-[#07101d]">{p.loading==='analysis'?'Analysing…':'Run linguistic analysis'}</button><button disabled={!!p.loading} onClick={p.runDossier} className="rounded-xl border border-emerald-700/60 bg-emerald-500/10 px-4 py-3 font-semibold text-emerald-200">{p.loading==='dossier'?'Building dossier…':'Full forensic dossier'}</button></div></section>
 <section className="rounded-2xl border border-amber-900/50 bg-white/[.02] p-5"><div className="flex items-center justify-between"><div><h2 className="font-semibold">Forced-language experiment</h2><p className="mt-1 text-xs text-slate-500">A controlled hypothesis test—not evidence of original composition.</p></div><Sparkles className="text-[#d8bd82]" size={18}/></div><div className="mt-4 grid gap-3 md:grid-cols-2"><select value={p.forcedLanguage} onChange={(e:any)=>p.setForcedLanguage(e.target.value)} className="rounded-lg border border-slate-700 bg-slate-950 p-3 text-sm"><option value="">Select target language…</option>{LANGUAGES.map(x=><option key={x}>{x}</option>)}</select><select value={p.probeMode} onChange={(e:any)=>p.setProbeMode(e.target.value)} className="rounded-lg border border-slate-700 bg-slate-950 p-3 text-sm"><option value="translate">Generate controlled reading</option><option value="evaluate">Evaluate supplied translation</option></select></div>{p.probeMode==='evaluate'&&<textarea value={p.translation} onChange={(e:any)=>p.setTranslation(e.target.value)} placeholder="Paste the translation to evaluate…" className="mt-3 min-h-24 w-full rounded-lg border border-slate-700 bg-slate-950 p-3 text-sm"/>}<button disabled={!!p.loading} onClick={p.runProbe} className="mt-3 w-full rounded-lg border border-amber-700/50 px-4 py-3 text-sm font-semibold text-amber-200">{p.loading==='probe'?'Running controlled probe…':'Run forced-language probe'}</button>{p.probe&&<div className="mt-4 space-y-3">{[['Target-language wording',p.probe.forced_text],['Transliteration',p.probe.transliteration],['English translation',p.probe.english_translation],['Arabic literal translation',p.probe.arabic_literal_translation],['Back-translation / semantic shift',p.probe.back_translation],['Plausibility',p.probe.plausibility]].map(([a,b])=><div key={a as string} className="rounded-lg border border-slate-800 bg-slate-950 p-3"><div className="text-[10px] uppercase tracking-wider text-slate-500">{a}</div><p dir="auto" className="mt-1 whitespace-pre-wrap text-sm leading-6 text-slate-300">{b}</p></div>)}<div className="rounded-lg border border-amber-900/50 bg-amber-950/20 p-3 text-xs text-amber-200/80">Controlled experiment only. A successful translation into a language does not demonstrate that the Arabic witness borrowed from it.</div></div>}</section>
 {p.analysis&&<section className="rounded-2xl border border-cyan-900/50 bg-white/[.02] p-5"><div className="flex justify-between gap-4"><h2 className="font-semibold">Linguistic analysis</h2><span className="text-xs text-cyan-300">{p.analysis.detected_language} · {Math.round(p.analysis.detection_confidence*100)}%</span></div><p className="mt-3 text-sm leading-6 text-slate-300">{p.analysis.summary}</p><div className="mt-4 space-y-2">{p.analysis.findings.map((f:any,i:number)=><div key={i} className="rounded-lg border border-slate-800 bg-slate-950 p-3 text-sm"><b>{f.text}</b> → {f.language} · {f.classification}<p className="mt-1 text-slate-400">{f.evidence}</p><p className="mt-1 text-xs text-slate-600">{f.caveat}</p></div>)}</div></section>}
 {p.dossier&&<DossierView d={p.dossier}/>}</div>
 <aside className="space-y-5"><section className="rounded-2xl border border-white/10 bg-white/[.025] p-5"><button onClick={()=>p.setShowLang(!p.showLang)} className="flex w-full items-center justify-between text-sm font-semibold"><span className="flex items-center gap-2"><Languages size={17}/>Comparison languages ({p.selected.length})</span>{p.showLang?<ChevronUp size={17}/>:<ChevronDown size={17}/>}</button>{p.showLang&&<div className="mt-4 max-h-[520px] space-y-2 overflow-auto pr-1">{LANGUAGES.map(x=><label key={x} className="flex gap-2 rounded-lg border border-slate-800 p-2 text-xs text-slate-300"><input type="checkbox" checked={p.selected.includes(x)} onChange={()=>p.setSelected((s:string[])=>s.includes(x)?s.filter(y=>y!==x):[...s,x])} className="accent-amber-300"/>{x}</label>)}</div>}</section><div className="rounded-2xl border border-amber-900/40 bg-amber-950/10 p-5 text-xs leading-6 text-amber-200/70"><b className="text-amber-200">Research guardrails</b><ul className="mt-2 space-y-1"><li>• Witness ≠ reconstructed original</li><li>• Cognate ≠ borrowing</li><li>• Similarity ≠ proof of contact</li><li>• Forced reading ≠ provenance evidence</li><li>• Model confidence ≠ statistical probability</li></ul></div></aside></div></main>}

function DossierView({d}:{d:Dossier}){return <section className="rounded-2xl border border-emerald-900/60 bg-white/[.02] p-5"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="text-lg font-semibold text-emerald-200">Forensic evidence dossier</h2><p className="mt-1 text-xs text-slate-500">Witness-preserving and text-critical output.</p></div><span className="text-xs text-emerald-300">{d.detected_language} · {Math.round(d.detection_confidence*100)}%</span></div><div className="mt-4 grid gap-3 md:grid-cols-2"><Card title="Original witness" value={d.witness}/><Card title="Normalized comparison" value={d.normalized}/></div><div className="mt-5"><h3 className="font-semibold">Word-by-word / root analysis</h3><div className="mt-2 space-y-2">{d.word_analysis.map((w,i)=><div key={i} className="rounded-lg border border-slate-800 bg-slate-950 p-3"><b dir="auto" className="font-serif text-amber-200">{w.witness}</b><span className="ml-2 text-xs text-slate-500">{w.transliteration} · {w.root_or_lemma} · {w.gloss}</span><p className="mt-1 text-xs text-slate-600">{w.note}</p></div>)}</div></div><div className="mt-5 grid gap-5 md:grid-cols-2"><List title="Textual criticism" items={d.textual_criticism}/><List title="Root fallbacks" items={d.root_fallbacks}/></div><div className="mt-5"><h3 className="font-semibold">Comparative cognates</h3><div className="mt-2 space-y-2">{d.comparative_cognates.map((c,i)=><div key={i} className="rounded-lg border border-slate-800 bg-slate-950 p-3 text-xs"><b>{c.span} → {c.candidate}</b><span className="ml-2 text-cyan-300">{c.language}</span><p className="mt-1 text-slate-400">{c.classification}: {c.evidence}</p><p className="mt-1 text-slate-600">{c.caveat}</p></div>)}</div></div><div className="mt-5 grid gap-5 md:grid-cols-2"><div><h3 className="font-semibold">Analytical perspectives</h3>{d.provider_comparison.map((x,i)=><div key={i} className="mt-2 rounded-lg border border-slate-800 bg-slate-950 p-3 text-xs"><b>{x.perspective}</b><p className="mt-1 text-slate-400">{x.conclusion}</p></div>)}</div><div><h3 className="font-semibold">Synthesis</h3><p className="mt-2 text-sm leading-6 text-slate-300">{d.synthesis}</p><List title="Limitations" items={d.limitations}/></div></div><div className="mt-5 rounded-lg border border-amber-900/50 bg-amber-950/20 p-3 text-xs leading-5 text-amber-200/80">Experimental readings and cognate candidates require independent manuscript, historical and philological evidence before stronger conclusions are justified.</div></section>}
function Card({title,value}:{title:string;value:string}){return <div className="rounded-xl border border-slate-800 bg-slate-950 p-4"><div className="text-[10px] uppercase tracking-wider text-slate-500">{title}</div><p dir="auto" className="mt-2 whitespace-pre-wrap font-serif text-lg leading-8 text-slate-200">{value}</p></div>}
function List({title,items}:{title:string;items:string[]}){return <div><h3 className="font-semibold">{title}</h3><ul className="mt-2 space-y-1 text-xs leading-5 text-slate-500">{items.map((x,i)=><li key={i}>• {x}</li>)}</ul></div>}

function ManuscriptPage({manuscripts,loading,error,onReload,onUse}:{manuscripts:Manuscript[];loading:string;error:string;onReload:()=>void;onUse:(t:string)=>void}){return <main className="mx-auto max-w-7xl px-5 py-10 lg:px-8"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[#d8bd82]">Manuscripts</p><h1 className="serif mt-2 text-4xl text-white">Witness catalogue</h1><p className="mt-3 max-w-3xl text-slate-400">Institutional records and verified excerpts are kept distinct from normalization and analysis.</p></div><button onClick={onReload} className="rounded-lg border border-slate-700 px-4 py-2 text-sm">{loading==='manuscripts'?'Loading…':'Refresh corpus'}</button></div>{error&&<p className="mt-5 rounded-lg border border-red-900 bg-red-950/40 p-3 text-sm text-red-300">{error}</p>}<div className="mt-8 grid gap-4 lg:grid-cols-2">{manuscripts.map(m=><article key={m.id} className="rounded-2xl border border-white/10 bg-white/[.025] p-5"><div className="flex justify-between gap-3"><div><h2 className="font-semibold">{m.work}</h2><p className="mt-1 text-xs text-cyan-300">{m.collection} · {m.shelfmark}</p></div><span className="text-xs text-slate-500">{m.manuscript_date}</span></div><div className="mt-4 grid gap-2 text-xs text-slate-400 sm:grid-cols-2"><span>Language: {m.language}</span><span>Script: {m.script}</span><span>Diacritics: {m.diacritics_status}</span><span>Status: {m.witness_status}</span></div>{m.witness_excerpt&&<div className="mt-4 rounded-xl border border-amber-900/40 bg-amber-950/10 p-4"><div className="text-[10px] uppercase tracking-wider text-amber-300">Verified excerpt</div><p dir="auto" className="mt-2 font-serif text-lg leading-8 text-amber-100">{m.witness_excerpt}</p><button onClick={()=>onUse(m.witness_excerpt)} className="mt-3 rounded-lg border border-amber-700/50 px-3 py-2 text-xs text-amber-200">Use in Research Lab</button></div>}<p className="mt-4 text-xs leading-5 text-slate-500">{m.notes}</p><a className="mt-3 inline-block text-xs text-cyan-300 hover:underline" href={safeExternalUrl(m.source_url)} target="_blank" rel="noreferrer">Open institutional record ↗</a></article>)}</div></main>}

function MethodPage(){return <main className="mx-auto max-w-7xl px-5 py-16 lg:px-8"><p className="text-xs font-bold uppercase tracking-[.2em] text-[#d8bd82]">Methodology</p><h1 className="serif mt-2 text-5xl text-white">Evidence before interpretation.</h1><div className="mt-8 grid gap-4 md:grid-cols-2">{principles.map((x,i)=><div key={x} className="rounded-2xl border border-white/10 bg-white/[.025] p-6"><b className="text-[#d8bd82]">0{i+1}</b><p className="mt-3 leading-7 text-slate-300">{x}</p></div>)}</div><div className="mt-8 rounded-2xl border border-white/10 p-6"><h2 className="text-xl font-semibold">Research sequence</h2><p className="mt-3 leading-7 text-slate-400">Witness → diplomatic transcription → normalization → phonology → lexical analysis → comparative linguistics → textual criticism → assessment. Each layer should remain inspectable and reversible.</p></div></main>}
function PricingPage(){return <main className="mx-auto max-w-7xl px-5 py-16 lg:px-8"><p className="text-xs font-bold uppercase tracking-[.2em] text-[#d8bd82]">Access</p><h1 className="serif mt-2 text-5xl text-white">Research access that scales with use.</h1><p className="mt-4 max-w-2xl text-slate-400">Core research remains accessible in the free tier. Paid tiers are designed around research-operation capacity rather than artificial message limits.</p><div className="mt-10 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{[['Open Research','$0','20 operations / month'],['Researcher','$7.90','150 operations / month'],['Scholar','$14.90','500 operations / month'],['Professional','$29.90','1,500 operations / month']].map(x=><div key={x[0]} className="rounded-2xl border border-white/10 bg-white/[.025] p-6"><h2 className="font-semibold">{x[0]}</h2><div className="mt-4 text-3xl font-bold text-[#d8bd82]">{x[1]}</div><p className="mt-2 text-sm text-slate-400">{x[2]}</p></div>)}</div><p className="mt-6 text-sm text-slate-500">14-day trial and payment enforcement will be activated after account/billing infrastructure is connected.</p></main>}
export default App;